### ISSUE TITLE
Parallax displacement not working right or something

### ISSUE THREAD

**Issue by foxe245** [GO-Miles/parallaxLT#7]
So when I fixate a sprite it does not look flat like it normally does sorry for the crude screenshots my recording software broke
idk if it matters bc its above the version but here

flixel 5.5.0
haxe 2.5.2

![paracrap2](https://github.com/Itz-Miles/parallaxLT/assets/97311877/78bfa475-9e9d-4e5f-bbe5-981c46b9011f)
![parracrap](https://github.com/Itz-Miles/parallaxLT/assets/97311877/13b6d5f2-9366-4b38-8543-f5b696087f9f)

**Comment by lazyremixmanordummyplayinggmod** [comment]
1, 1, 0, 0, 1, 1, horizontal
in fixate

**Comment by Itz-Miles** [comment]
Thanks for reporting an issue, but the problems you are facing are due to an oversight on your arguments!
Your first two are setting camera offsets `anchorX` and `anchorY` to 0. To set the `scrollOneX` and `scrollOneY` values, it should be the third and fourth!
`fixate(0, 0, 1, 1, 1, 1, "horizontal");`

I understand that the fixate function is inconvenient to work with, so I plan on releasing an update that introduces variables you can set any way you'd like. https://github.com/Itz-Miles/parallaxLT/discussions/6

**Comment by lazyremixmanordummyplayinggmod** [comment]
i have tried that but it does nothing the sprite does not look right

**Comment by lazyremixmanordummyplayinggmod** [comment]
hold up i got to test tho jusy in case

**Comment by lazyremixmanordummyplayinggmod** [comment]
![pp](https://github.com/Itz-Miles/parallaxLT/assets/97311877/cdd3bfa6-b629-4b0c-a9b0-b53cdd77a1eb)
still it looks the same

**Comment by lazyremixmanordummyplayinggmod** [comment]
oh wait oh

**Comment by lazyremixmanordummyplayinggmod** [comment]
i understand

**Comment by lazyremixmanordummyplayinggmod** [comment]
you need a wiki for some of this so that its not confusing when changes happen

**Comment by lazyremixmanordummyplayinggmod** [comment]
it still looks liek the last image i sent tho

**Comment by Itz-Miles** [comment]
I know your concerns, so I'll be documenting key changes to haxefixel and the ParallaxSprites! [0.1.0](https://github.com/Itz-Miles/parallaxLT/discussions/6) will introduce proper variables you can get and set. Instead of having to pack all of your args into a single `fixate()` function, you'll be able to call things like `scrollFactor2.set()` if you want! Alongside 0.1.0, there will be a demos/wiki page that shows documentation and live examples for users to learn from.
